version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django-notes-app  # You can adjust the destination directory

hooks:
  AfterInstall:
    - location: docker-start.sh  # Script to start Docker services
      timeout: 300
      runas: root

  ApplicationStart:
    - location: docker-deploy.sh  # Script to deploy Docker container
      timeout: 300
      runas: root
